apiVersion: v1
kind: Secret
metadata:
  name: capstone-secrets
  namespace: capstone
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongo:27017/capstone"
  JWT_SECRET: "your-jwt-secret-change-in-production"
